language: php

php: 7

matrix:
  fast_finish: true

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "vendor"

before_install:
  - composer selfupdate

install:
  # Load composer dependencies.
  - composer validate --no-check-all --ansi
  - composer install --optimize-autoloader

before_script:
  # Verify that no git diffs (caused by line ending variation) exist.
  - git diff --exit-code

script:
  - ./scripts/run-tests.sh

after_success:
  - ./vendor/bin/coveralls -vvv
